"""Database schema, as numbered migrations. The SQL is the common subset of SQLite and PostgreSQL:
text ids made in Python, epoch milliseconds in BIGINT/INTEGER, JSON stored as TEXT, booleans as 0/1."""

MIGRATIONS = [
    (1, [
        """CREATE TABLE users (
            id TEXT PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            status TEXT NOT NULL DEFAULT 'active',
            plan TEXT NOT NULL DEFAULT 'free',
            disabled_reason TEXT,
            email_verified INTEGER NOT NULL DEFAULT 0,
            failed_logins INTEGER NOT NULL DEFAULT 0,
            locked_until BIGINT NOT NULL DEFAULT 0,
            created_at BIGINT NOT NULL,
            last_login_at BIGINT)""",
        "CREATE INDEX users_role ON users (role, status)",
        """CREATE TABLE plans (
            name TEXT PRIMARY KEY,
            description TEXT NOT NULL DEFAULT '',
            tokens_per_day BIGINT, tokens_per_month BIGINT, requests_per_minute INTEGER,
            max_conlangs INTEGER, max_output_tokens INTEGER)""",
        """CREATE TABLE user_limits (
            user_id TEXT PRIMARY KEY REFERENCES users (id),
            tokens_per_day BIGINT, tokens_per_month BIGINT, requests_per_minute INTEGER,
            max_conlangs INTEGER, max_output_tokens INTEGER,
            updated_by TEXT, updated_at BIGINT)""",
        """CREATE TABLE refresh_tokens (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL REFERENCES users (id),
            family_id TEXT NOT NULL,
            token_hash TEXT NOT NULL UNIQUE,
            created_at BIGINT NOT NULL,
            expires_at BIGINT NOT NULL,
            revoked_at BIGINT,
            replaced_by TEXT,
            user_agent TEXT)""",
        "CREATE INDEX refresh_user ON refresh_tokens (user_id)",
        """CREATE TABLE conlangs (
            id TEXT PRIMARY KEY,
            owner_id TEXT NOT NULL REFERENCES users (id),
            name TEXT NOT NULL,
            seed BIGINT,
            vocab_version TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            spec_json TEXT,
            language_json TEXT,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL)""",
        "CREATE INDEX conlangs_owner ON conlangs (owner_id, status)",
        """CREATE TABLE quota_counters (
            user_id TEXT NOT NULL,
            period_kind TEXT NOT NULL,
            period_key TEXT NOT NULL,
            used BIGINT NOT NULL DEFAULT 0,
            reserved BIGINT NOT NULL DEFAULT 0,
            requests INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, period_kind, period_key))""",
        """CREATE TABLE quota_reservations (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            amount BIGINT NOT NULL,
            day_key TEXT NOT NULL,
            month_key TEXT NOT NULL,
            created_at BIGINT NOT NULL)""",
        """CREATE TABLE llm_calls (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            conlang_id TEXT,
            job_id TEXT,
            purpose TEXT NOT NULL,
            provider TEXT,
            model TEXT,
            status TEXT NOT NULL,
            error_code TEXT,
            input_tokens BIGINT NOT NULL DEFAULT 0,
            output_tokens BIGINT NOT NULL DEFAULT 0,
            cache_write_tokens BIGINT NOT NULL DEFAULT 0,
            cache_read_tokens BIGINT NOT NULL DEFAULT 0,
            quota_tokens BIGINT NOT NULL DEFAULT 0,
            cost_micro_usd BIGINT NOT NULL DEFAULT 0,
            latency_ms INTEGER NOT NULL DEFAULT 0,
            attempts INTEGER NOT NULL DEFAULT 0,
            request_chars INTEGER NOT NULL DEFAULT 0,
            response_chars INTEGER NOT NULL DEFAULT 0,
            preview_json TEXT,
            created_at BIGINT NOT NULL)""",
        "CREATE INDEX llm_calls_time ON llm_calls (created_at)",
        "CREATE INDEX llm_calls_user_time ON llm_calls (user_id, created_at)",
        "CREATE INDEX llm_calls_purpose_time ON llm_calls (purpose, created_at)",
        """CREATE TABLE audit_log (
            id TEXT PRIMARY KEY,
            actor_id TEXT,
            action TEXT NOT NULL,
            target_type TEXT,
            target_id TEXT,
            detail_json TEXT,
            created_at BIGINT NOT NULL)""",
        "CREATE INDEX audit_time ON audit_log (created_at)",
        "CREATE INDEX audit_target ON audit_log (target_type, target_id)",
        "CREATE TABLE settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_by TEXT, updated_at BIGINT)",
    ]),
    (2, [
        "ALTER TABLE users ADD COLUMN password_set INTEGER NOT NULL DEFAULT 1",
        """CREATE TABLE identities (
            provider TEXT NOT NULL,
            subject TEXT NOT NULL,
            user_id TEXT NOT NULL REFERENCES users (id),
            email TEXT,
            created_at BIGINT NOT NULL,
            last_login_at BIGINT,
            PRIMARY KEY (provider, subject))""",
        "CREATE INDEX identities_user ON identities (user_id)",
    ]),
]
